"""Add photo column to students table

Revision ID: 18865ba5fc40
Revises: 5892a86d1a6e
Create Date: 2025-09-28 19:14:41.080865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18865ba5fc40'
down_revision: Union[str, None] = '5892a86d1a6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('photo', sa.LargeBinary(), nullable=True))
    op.drop_column('students', 'aadhar_number')
    op.drop_column('students', 'identification_mark')
    op.drop_column('students', 'type_of_disability')
    op.drop_column('students', 'percent_of_disability')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('percent_of_disability', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('type_of_disability', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('identification_mark', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('aadhar_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('students', 'photo')
    # ### end Alembic commands ###
