"""add_email_and_class_assignments_to_teachers

Revision ID: 3f5f6f7937c8
Revises: 6387b3cd2064
Create Date: 2025-08-04 22:08:02.418523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f5f6f7937c8'
down_revision: Union[str, None] = '6387b3cd2064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('email', sa.String(), nullable=True))
    op.add_column('teachers', sa.Column('class_assignments', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'class_assignments')
    op.drop_column('teachers', 'email')
    # ### end Alembic commands ###
