"""create therapy_reports table

Revision ID: 616d15931db4
Revises: f2a3b4c5d6e7
Create Date: 2025-10-05 23:15:42.048494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '616d15931db4'
down_revision: Union[str, None] = 'f2a3b4c5d6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "therapy_reports",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("student_id", sa.Integer(), sa.ForeignKey("students.id", ondelete="CASCADE"), nullable=False),
        sa.Column("teacher_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="SET NULL"), nullable=True),
        sa.Column("report_date", sa.Date(), nullable=False),
        sa.Column("therapy_type", sa.String(length=255), nullable=True),
        sa.Column("progress_notes", sa.Text(), nullable=True),
        sa.Column("goals_achieved", sa.Text(), nullable=True),
        sa.Column("progress_level", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    )
    op.create_index(op.f('ix_therapy_reports_student_id'), 'therapy_reports', ['student_id'], unique=False)
    op.create_index(op.f('ix_therapy_reports_teacher_id'), 'therapy_reports', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_therapy_reports_teacher_id'), table_name='therapy_reports')
    op.drop_index(op.f('ix_therapy_reports_student_id'), table_name='therapy_reports')
    op.drop_table('therapy_reports')
    # ### end Alembic commands ###
