"""Add block_panchayat, local_body, taluk to students table

Revision ID: a211076f3938
Revises: 874f87705c7c
Create Date: 2025-09-20 13:04:10.928539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a211076f3938'
down_revision: Union[str, None] = '874f87705c7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('block_panchayat', sa.String(), nullable=True))
    op.add_column('students', sa.Column('local_body', sa.String(), nullable=True))
    op.add_column('students', sa.Column('taluk', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'taluk')
    op.drop_column('students', 'local_body')
    op.drop_column('students', 'block_panchayat')
    # ### end Alembic commands ###
