"""Add aadhar_number to students table

Revision ID: bd31cd7a5f01
Revises: cea570b0165a
Create Date: 2025-09-30 18:01:37.642351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd31cd7a5f01'
down_revision: Union[str, None] = 'cea570b0165a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('aadhar_number', sa.String(), nullable=True))
    op.create_index(op.f('ix_students_aadhar_number'), 'students', ['aadhar_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_aadhar_number'), table_name='students')
    op.drop_column('students', 'aadhar_number')
    # ### end Alembic commands ###
