"""Add all case record fields to students table

Revision ID: d01b167c44cc
Revises: d0f612cad1ce
Create Date: 2025-10-04 22:27:08.013636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd01b167c44cc'
down_revision: Union[str, None] = 'd0f612cad1ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('guardian_occupation', sa.String(), nullable=True))
    op.add_column('students', sa.Column('total_family_income', sa.String(), nullable=True))
    op.add_column('students', sa.Column('address_and_phone', sa.String(), nullable=True))
    op.add_column('students', sa.Column('informant_name', sa.String(), nullable=True))
    op.add_column('students', sa.Column('informant_relationship', sa.String(), nullable=True))
    op.add_column('students', sa.Column('duration_of_contact', sa.String(), nullable=True))
    op.add_column('students', sa.Column('present_complaints', sa.Text(), nullable=True))
    op.add_column('students', sa.Column('previous_treatments', sa.Text(), nullable=True))
    op.add_column('students', sa.Column('family_history_mental_illness', sa.Text(), nullable=True))
    op.add_column('students', sa.Column('family_history_mental_retardation', sa.Text(), nullable=True))
    op.add_column('students', sa.Column('family_history_epilepsy', sa.Text(), nullable=True))
    op.add_column('students', sa.Column('prenatal_history', sa.Text(), nullable=True))
    op.add_column('students', sa.Column('natal_history', sa.Text(), nullable=True))
    op.add_column('students', sa.Column('postnatal_history', sa.Text(), nullable=True))
    op.add_column('students', sa.Column('smiles_at_other', sa.Boolean(), nullable=True))
    op.add_column('students', sa.Column('head_control', sa.Boolean(), nullable=True))
    op.add_column('students', sa.Column('sitting', sa.Boolean(), nullable=True))
    op.add_column('students', sa.Column('responds_to_name', sa.Boolean(), nullable=True))
    op.add_column('students', sa.Column('babbling', sa.Boolean(), nullable=True))
    op.add_column('students', sa.Column('first_words', sa.Boolean(), nullable=True))
    op.add_column('students', sa.Column('standing', sa.Boolean(), nullable=True))
    op.add_column('students', sa.Column('walking', sa.Boolean(), nullable=True))
    op.add_column('students', sa.Column('two_word_phrases', sa.Boolean(), nullable=True))
    op.add_column('students', sa.Column('toilet_control', sa.Boolean(), nullable=True))
    op.add_column('students', sa.Column('sentences', sa.Boolean(), nullable=True))
    op.add_column('students', sa.Column('physical_deformity', sa.Boolean(), nullable=True))
    op.add_column('students', sa.Column('school_history', sa.Text(), nullable=True))
    op.add_column('students', sa.Column('occupational_history', sa.Text(), nullable=True))
    op.add_column('students', sa.Column('behaviour_problems', sa.Text(), nullable=True))
    op.add_column('students', sa.Column('psychological_assessment', sa.Text(), nullable=True))
    op.add_column('students', sa.Column('medical_examination', sa.Text(), nullable=True))
    op.add_column('students', sa.Column('diagnosis', sa.Text(), nullable=True))
    op.add_column('students', sa.Column('management_plan', sa.Text(), nullable=True))
    op.add_column('students', sa.Column('specific_diagnostic', sa.Text(), nullable=True))
    op.add_column('students', sa.Column('is_on_regular_drugs', sa.String(), nullable=True))
    op.add_column('students', sa.Column('drug_allergy', sa.String(), nullable=True))
    op.add_column('students', sa.Column('food_allergy', sa.String(), nullable=True))
    op.alter_column('students', 'medical_conditions',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('students', 'allergies',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'allergies',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('students', 'medical_conditions',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('students', 'food_allergy')
    op.drop_column('students', 'drug_allergy')
    op.drop_column('students', 'is_on_regular_drugs')
    op.drop_column('students', 'specific_diagnostic')
    op.drop_column('students', 'management_plan')
    op.drop_column('students', 'diagnosis')
    op.drop_column('students', 'medical_examination')
    op.drop_column('students', 'psychological_assessment')
    op.drop_column('students', 'behaviour_problems')
    op.drop_column('students', 'occupational_history')
    op.drop_column('students', 'school_history')
    op.drop_column('students', 'physical_deformity')
    op.drop_column('students', 'sentences')
    op.drop_column('students', 'toilet_control')
    op.drop_column('students', 'two_word_phrases')
    op.drop_column('students', 'walking')
    op.drop_column('students', 'standing')
    op.drop_column('students', 'first_words')
    op.drop_column('students', 'babbling')
    op.drop_column('students', 'responds_to_name')
    op.drop_column('students', 'sitting')
    op.drop_column('students', 'head_control')
    op.drop_column('students', 'smiles_at_other')
    op.drop_column('students', 'postnatal_history')
    op.drop_column('students', 'natal_history')
    op.drop_column('students', 'prenatal_history')
    op.drop_column('students', 'family_history_epilepsy')
    op.drop_column('students', 'family_history_mental_retardation')
    op.drop_column('students', 'family_history_mental_illness')
    op.drop_column('students', 'previous_treatments')
    op.drop_column('students', 'present_complaints')
    op.drop_column('students', 'duration_of_contact')
    op.drop_column('students', 'informant_relationship')
    op.drop_column('students', 'informant_name')
    op.drop_column('students', 'address_and_phone')
    op.drop_column('students', 'total_family_income')
    op.drop_column('students', 'guardian_occupation')
    # ### end Alembic commands ###
