"""add category and blood group to students

Revision ID: d0f612cad1ce
Revises: df56cd9934b0
Create Date: 2025-10-04 12:19:11.114211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0f612cad1ce'
down_revision: Union[str, None] = 'df56cd9934b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('category', sa.String(), nullable=True))
    op.add_column('students', sa.Column('blood_group', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'blood_group')
    op.drop_column('students', 'category')
    # ### end Alembic commands ###
