"""add_headmistress_role_to_users

Revision ID: d7f8b2c678e5
Revises: 3f5f6f7937c8
Create Date: 2025-08-04 22:54:42.859869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7f8b2c678e5'
down_revision: Union[str, None] = '3f5f6f7937c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
