"""Add identification_marks to students

Revision ID: df56cd9934b0
Revises: 6ba99e487fb3
Create Date: 2025-09-30 20:38:25.762609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df56cd9934b0'
down_revision: Union[str, None] = '6ba99e487fb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('identification_marks', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'identification_marks')
    # ### end Alembic commands ###
