"""add aadhar_number, type_of_disability, percent_of_disability, identification_mark to students

Revision ID: e381a6a50391
Revises: a211076f3938
Create Date: 2025-09-20 13:50:41.455016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e381a6a50391'
down_revision: Union[str, None] = 'a211076f3938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('aadhar_number', sa.String(), nullable=True))
    op.add_column('students', sa.Column('type_of_disability', sa.String(), nullable=True))
    op.add_column('students', sa.Column('percent_of_disability', sa.Float(), nullable=True))
    op.add_column('students', sa.Column('identification_mark', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'identification_mark')
    op.drop_column('students', 'percent_of_disability')
    op.drop_column('students', 'type_of_disability')
    op.drop_column('students', 'aadhar_number')
    # ### end Alembic commands ###
